# This is a basic workflow to help you get started with Actions

name: run and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - run: javac -cp lib/junit-4.13.2.jar:. *.java
      - run: java -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:." org.junit.runner.JUnitCore MarkdownParseTest
